<template>
  <section>
    <div class="page-heading">
      <div><p class="eyebrow">LIVE TELEMETRY / {{ formatTime(snapshot.timestamp) }}</p><h1>实时运行总览</h1><p class="subtext">聚合查看所有采集节点的系统、容器与微服务健康状态。</p></div>
      <div class="connection" :class="connected ? 'is-online' : 'is-offline'"><span class="pulse" />{{ connected ? '实时连接中' : '连接断开，自动重试' }}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-card summary-card--accent"><span>在线节点</span><strong>{{ clients.length }}</strong><small>当前有数据上报的客户端</small></div>
      <div class="summary-card"><span>运行容器</span><strong>{{ totalRunning }}</strong><small>来自 {{ clientsWithDocker }} 个节点</small></div>
      <div class="summary-card"><span>健康微服务</span><strong>{{ healthyServices }}</strong><small>共 {{ totalServices }} 个检查项</small></div>
      <div class="summary-card"><span>数据刷新</span><strong>{{ lastUpdateLabel }}</strong><small>WebSocket / 3 秒推送</small></div>
    </div>

    <div class="display-alerts" :class="{ 'display-alerts--normal': !activeAlerts.length }"><div class="display-alerts__title"><span><i class="el-icon-bell" /> 告警状态</span><el-tag size="mini" :type="activeAlerts.length ? 'danger' : 'success'">{{ activeAlerts.length ? `${activeAlerts.length} 条待处理` : '运行正常' }}</el-tag></div><div v-if="activeAlerts.length" class="display-alert-list"><div v-for="event in activeAlerts.slice(0, 4)" :key="`${event.ruleId}-${event.clientId}`" class="display-alert" :class="event.level === 'CRITICAL' ? 'display-alert--critical' : ''"><i class="el-icon-warning-outline" /><span>{{ event.message }}</span><small>{{ event.level }}</small></div><div v-if="activeAlerts.length > 4" class="display-alert-more">还有 {{ activeAlerts.length - 4 }} 条告警，请前往后台管理查看</div></div><div v-else class="display-alert-normal">当前没有触发的告警规则</div></div>

    <div v-if="!clients.length" class="empty-state"><i class="el-icon-connection" /><h3>等待采集节点上线</h3><p>请启动 monitor-client，数据将通过 WebSocket 自动出现在这里。</p><el-button type="primary" plain @click="loadSnapshot">立即刷新</el-button></div>
      <div v-for="client in clients" :key="client.clientId" class="client-panel">
      <div class="client-panel__head"><div><span class="node-dot" /><b>{{ displayName(client) }}</b><code>{{ client.clientId }}</code></div><el-tag size="mini" type="success">ONLINE</el-tag></div>
      <div class="tabs"><button v-for="tab in visibleTabs(client)" :key="tab.key" :class="{ active: activeTabs[client.clientId] === tab.key }" @click="selectTab(client.clientId, tab.key)">{{ tab.label }}</button></div>
      <div v-if="activeTabs[client.clientId] === 'system'" class="metrics-grid">
        <metric-card v-for="item in systemMetrics(client)" :key="item.label" v-bind="item" />
      </div>
      <div v-else-if="activeTabs[client.clientId] === 'docker'"><div v-if="!hasDocker(client)" class="panel-empty">Docker 未启用或暂无采集数据</div><template v-else><div class="metrics-grid compact"><metric-card label="容器总数" :value="docker(client).totalContainers" unit="个" icon="el-icon-box" /><metric-card label="运行中" :value="docker(client).runningContainers" unit="个" tone="green" icon="el-icon-video-play" /><metric-card label="异常" :value="docker(client).unhealthyContainers" unit="个" tone="red" icon="el-icon-warning" /></div><data-table :columns="dockerColumns" :rows="docker(client).containers || []" /></template></div>
      <div v-else><div v-if="!hasServices(client)" class="panel-empty">微服务监控未启用或暂无采集数据</div><template v-else><div class="metrics-grid compact"><metric-card label="服务总数" :value="services(client).totalServices" unit="个" icon="el-icon-s-grid" /><metric-card label="健康" :value="services(client).healthyServices" unit="个" tone="green" icon="el-icon-success" /><metric-card label="异常" :value="services(client).unhealthyServices" unit="个" tone="red" icon="el-icon-warning" /></div><data-table :columns="serviceColumns" :rows="services(client).services || []" /></template></div>
    </div>
  </section>
</template>
<script>
import MetricCard from '../components/MetricCard.vue'
import { getSnapshot, getPublicNodeConfigs, getActiveAlerts, websocketUrl } from '../services/monitor'

const DataTable = { props: ['columns', 'rows'], template: '<div v-if="rows.length" class="data-table-wrap"><table class="data-table"><thead><tr><th v-for="c in columns" :key="c.key">{{ c.label }}</th></tr></thead><tbody><tr v-for="(row, i) in rows" :key="i"><td v-for="c in columns" :key="c.key"><span v-if="c.type === \'status\'" :class="[\'status-tag\', row[c.key] === \'UP\' || row[c.key] === \'running\' ? \'ok\' : \'bad\']">{{ row[c.key] || \'UNKNOWN\' }}</span><span v-else>{{ row[c.key] === undefined || row[c.key] === null || row[c.key] === \'\' ? \'-\' : row[c.key] }}</span></td></tr></tbody></table></div><div v-else class="panel-empty">暂无明细数据</div>' }

export default {
  components: { MetricCard, DataTable },
  data: () => ({ snapshot: { clientSnapshots: [], onlineClients: [] }, activeAlerts: [], connected: false, socket: null, reconnectTimer: null, alertTimer: null, lastUpdate: null, activeTabs: {}, nodeConfigs: {}, settings: { warning: 70, critical: 90 }, tabs: [{ key: 'system', label: '系统指标' }, { key: 'docker', label: 'Docker 容器' }, { key: 'services', label: '微服务' }], dockerColumns: [{ key: 'name', label: '容器' }, { key: 'image', label: '镜像' }, { key: 'status', label: '状态', type: 'status' }, { key: 'cpuUsage', label: 'CPU %' }, { key: 'memoryUsageMB', label: '内存 MB' }, { key: 'ports', label: '端口' }], serviceColumns: [{ key: 'serviceName', label: '服务' }, { key: 'serviceUrl', label: '检查地址' }, { key: 'healthStatus', label: '状态', type: 'status' }, { key: 'responseTimeMs', label: '响应 ms' }, { key: 'errorMessage', label: '错误信息' }] }),
  computed: { clients () { return (this.snapshot.clientSnapshots || []).filter(c => !this.nodeConfigs[c.clientId] || this.nodeConfigs[c.clientId].enabled !== false) }, totalRunning () { return this.clients.reduce((n, c) => n + (this.docker(c).runningContainers || 0), 0) }, clientsWithDocker () { return this.clients.filter(this.hasDocker).length }, healthyServices () { return this.clients.reduce((n, c) => n + (this.services(c).healthyServices || 0), 0) }, totalServices () { return this.clients.reduce((n, c) => n + (this.services(c).totalServices || 0), 0) }, lastUpdateLabel () { return this.lastUpdate ? `${Math.max(0, Math.round((Date.now() - this.lastUpdate) / 1000))}s 前` : '-' } },
  mounted () { this.loadNodeConfigs(); this.loadSnapshot(); this.loadActiveAlerts(); this.alertTimer = setInterval(this.loadActiveAlerts, 5000); this.connect() }, beforeDestroy () { clearTimeout(this.reconnectTimer); clearInterval(this.alertTimer); if (this.socket) this.socket.close() },
  methods: {
    loadNodeConfigs () { getPublicNodeConfigs().then(rows => { const map = {}; (rows || []).forEach(row => { map[row.clientId] = row }); this.nodeConfigs = map }).catch(() => {}) }, loadActiveAlerts () { getActiveAlerts().then(data => { this.activeAlerts = data || [] }).catch(() => {}) }, loadSnapshot () { getSnapshot().then(this.applySnapshot).catch(() => {}) }, applySnapshot (data) { this.snapshot = data || {}; this.lastUpdate = Date.now(); (this.clients || []).forEach(c => { if (!this.activeTabs[c.clientId]) this.$set(this.activeTabs, c.clientId, this.defaultTab(c)) }) },
    connect () { try { this.socket = new WebSocket(websocketUrl()); this.socket.onopen = () => { this.connected = true }; this.socket.onmessage = e => { try { this.applySnapshot(JSON.parse(e.data)) } catch (_) {} }; this.socket.onclose = () => { this.connected = false; this.reconnectTimer = setTimeout(() => this.connect(), 3000) }; this.socket.onerror = () => this.socket.close() } catch (_) { this.connected = false; this.reconnectTimer = setTimeout(() => this.connect(), 3000) } },
    selectTab (id, tab) { this.$set(this.activeTabs, id, tab) }, displayName (c) { return (this.nodeConfigs[c.clientId] && this.nodeConfigs[c.clientId].displayName) || c.hostname || c.clientId }, visibleTabs (c) { const config = this.nodeConfigs[c.clientId]; if (!config) return this.tabs; return this.tabs.filter(tab => tab.key === 'system' ? config.displaySystem !== false : tab.key === 'docker' ? config.displayDocker !== false : config.displayMicroservice !== false) }, defaultTab (c) { const visible = this.visibleTabs(c); return visible.length ? visible[0].key : 'system' }, docker (c) { return c.dockerMetrics || {} }, services (c) { return c.microserviceMetrics || {} }, hasDocker (c) { return this.docker(c).totalContainers !== undefined && this.docker(c).totalContainers >= 0 }, hasServices (c) { return this.services(c).totalServices !== undefined && this.services(c).totalServices >= 0 }, formatTime (v) { return v ? String(v).replace('T', ' ') : '--' }, num (v) { return Number(v || 0).toFixed(1) },
    systemMetrics (c) { const s = c.systemMetrics || {}; return [{ label: 'CPU 使用率', value: this.num(s.cpuUsage), unit: '%', progress: s.cpuUsage || 0, tone: this.tone(s.cpuUsage), icon: 'el-icon-cpu' }, { label: '内存使用率', value: this.num(s.memoryUsage), unit: '%', progress: s.memoryUsage || 0, tone: this.tone(s.memoryUsage), icon: 'el-icon-odometer' }, { label: '磁盘使用率', value: this.num(s.diskUsage), unit: '%', progress: s.diskUsage || 0, tone: this.tone(s.diskUsage), icon: 'el-icon-files' }, { label: 'JVM 堆使用', value: this.num(s.jvmHeapUsage), unit: '%', progress: s.jvmHeapUsage || 0, tone: this.tone(s.jvmHeapUsage), icon: 'el-icon-data-line' }, { label: '网络接收', value: this.num(s.networkRxKBs), unit: 'KB/s', icon: 'el-icon-download' }, { label: '网络发送', value: this.num(s.networkTxKBs), unit: 'KB/s', icon: 'el-icon-upload' }] }, tone (v) { return v > this.settings.critical ? 'red' : v > this.settings.warning ? 'yellow' : 'green' }
  }
}
</script>
